/**
 * Snipcart API Utilities
 * 
 * This module provides utility functions for interacting with the Snipcart API.
 * It handles validation, fetching payment sessions, and confirming payments.
 * 
 * @module lib/snipcart
 */

const SNIPCART_API_BASE = 'https://app.snipcart.com/api';

/**
 * Gets the Snipcart secret API key from environment variables
 * 
 * @returns {string} The API key
 * @throws {Error} If the API key is not configured
 */
function getApiKey() {
  const apiKey = process.env.SNIPCART_SECRET_API_KEY;
  if (!apiKey) {
    throw new Error('SNIPCART_SECRET_API_KEY environment variable is not set');
  }
  return apiKey;
}

/**
 * Makes an authenticated request to the Snipcart API
 * 
 * @param {string} endpoint - API endpoint (without base URL)
 * @param {Object} options - Fetch options
 * @returns {Promise<Object>} The API response
 * @throws {Error} If the request fails
 */
async function snipcartRequest(endpoint, options = {}) {
  const apiKey = getApiKey();
  const url = `${SNIPCART_API_BASE}${endpoint}`;
  
  // Encode API key as base64 for Basic auth
  const authHeader = `Basic ${Buffer.from(apiKey + ':').toString('base64')}`;
  
  const response = await fetch(url, {
    ...options,
    headers: {
      'Authorization': authHeader,
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      ...options.headers
    }
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error(`Snipcart API error [${response.status}]:`, errorText);
    throw new Error(`Snipcart API request failed: ${response.status} ${response.statusText}`);
  }

  return response.json();
}

/**
 * Validates a Snipcart public token
 * 
 * Public tokens are single-use tokens generated by Snipcart for each payment session.
 * This function validates that the token exists and is valid.
 * 
 * @param {string} publicToken - The public token to validate
 * @returns {Promise<boolean>} True if valid, false otherwise
 */
async function validatePublicToken(publicToken) {
  if (!publicToken) {
    console.error('[Snipcart] No public token provided');
    return false;
  }

  try {
    // Fetch the payment session to validate the token
    const session = await getPaymentSession(publicToken);
    
    // If we got a session back, the token is valid
    return !!session;
  } catch (error) {
    console.error('[Snipcart] Token validation failed:', error.message);
    return false;
  }
}

/**
 * Fetches payment session details from Snipcart
 * 
 * This retrieves the full payment session information, including:
 * - Invoice details (amount, currency, items)
 * - Customer information
 * - Shipping details
 * - Tax calculations
 * 
 * **IMPORTANT**: Always fetch amounts server-side. Never trust client-provided amounts.
 * 
 * @param {string} publicToken - The public token for the payment session
 * @returns {Promise<Object>} The payment session details
 * @throws {Error} If the session cannot be retrieved
 */
async function getPaymentSession(publicToken) {
  if (!publicToken) {
    throw new Error('Public token is required');
  }

  try {
    // The payment session endpoint uses the public token
    const session = await snipcartRequest(`/sessions/${publicToken}`);
    
    console.log('[Snipcart] Retrieved payment session:', {
      token: publicToken.substring(0, 20) + '...',
      total: session.invoice?.total,
      currency: session.invoice?.currency
    });

    return session;
  } catch (error) {
    console.error('[Snipcart] Failed to get payment session:', error.message);
    throw new Error(`Failed to retrieve payment session: ${error.message}`);
  }
}

/**
 * Confirms a payment with Snipcart
 * 
 * This notifies Snipcart that the payment was successful and provides the transaction ID.
 * This is critical to prevent orders from remaining in "pending" state.
 * 
 * **MUST** be called after receiving successful payment webhook from processor.
 * 
 * @param {string} publicToken - The public token for the payment session
 * @param {string} transactionId - The payment processor's transaction ID
 * @returns {Promise<Object>} The confirmation response
 * @throws {Error} If the confirmation fails
 */
async function confirmPayment(publicToken, transactionId) {
  if (!publicToken) {
    throw new Error('Public token is required');
  }
  if (!transactionId) {
    throw new Error('Transaction ID is required');
  }

  try {
    // Confirm the payment with Snipcart
    // This endpoint marks the order as paid and completes the checkout
    const result = await snipcartRequest(`/sessions/${publicToken}`, {
      method: 'PATCH',
      body: JSON.stringify({
        state: 'Processed',
        transactionId: transactionId
      })
    });

    console.log('[Snipcart] Payment confirmed:', {
      token: publicToken.substring(0, 20) + '...',
      transactionId: transactionId
    });

    return result;
  } catch (error) {
    console.error('[Snipcart] Failed to confirm payment:', error.message);
    throw new Error(`Failed to confirm payment: ${error.message}`);
  }
}

/**
 * Marks a payment as failed in Snipcart
 * 
 * @param {string} publicToken - The public token for the payment session
 * @param {string} errorMessage - Description of why the payment failed
 * @returns {Promise<Object>} The response
 */
async function markPaymentFailed(publicToken, errorMessage) {
  if (!publicToken) {
    throw new Error('Public token is required');
  }

  try {
    const result = await snipcartRequest(`/sessions/${publicToken}`, {
      method: 'PATCH',
      body: JSON.stringify({
        state: 'Failed',
        error: errorMessage
      })
    });

    console.log('[Snipcart] Payment marked as failed:', {
      token: publicToken.substring(0, 20) + '...',
      error: errorMessage
    });

    return result;
  } catch (error) {
    console.error('[Snipcart] Failed to mark payment as failed:', error.message);
    throw new Error(`Failed to mark payment as failed: ${error.message}`);
  }
}

module.exports = {
  validatePublicToken,
  getPaymentSession,
  confirmPayment,
  markPaymentFailed
};
